//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_DotNet_Lasalle_College
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class BookInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookInfo()
        {
            this.IssueBooks = new HashSet<IssueBook>();
        }
    
        [DisplayName("Book Name:")]
        public int b_id { get; set; }
        public string b_name { get; set; }
        public Nullable<int> aut_id { get; set; }
        public Nullable<int> pub_id { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> pages { get; set; }
    
        public virtual author author { get; set; }
        public virtual category category { get; set; }
        public virtual publisher publisher { get; set; }
        public virtual BookInfo BookInfo1 { get; set; }
        public virtual BookInfo BookInfo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueBook> IssueBooks { get; set; }
    }
}
