//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_DotNet_Lasalle_College
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueBook
    {
        public int id { get; set; }
        public Nullable<int> m_id { get; set; }
        public Nullable<int> b_id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual BookInfo BookInfo { get; set; }
        public virtual MemberInfo MemberInfo { get; set; }
    }
}
